checkout_checkout:
    path:     /checkout
    defaults: { _controller: UniversalIDTBundle:Checkout:checkout }

checkout_result:
    path:     /checkout/result
    defaults: { _controller: UniversalIDTBundle:Checkout:paymentResult }

checkout_basket:
    path:     /basket
    defaults: { _controller: UniversalIDTBundle:Checkout:basket }

checkout_test:
    path:     /test
    defaults: { _controller: UniversalIDTBundle:Checkout:test }