fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /

fos_user_profile_show:
    path:     /app/setting/profile
    defaults: { _controller: FOSUserBundle:Profile:edit }

fos_user_profile_edit:
    path:     /app/setting/profile
    defaults: { _controller: FOSUserBundle:Profile:edit }

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /

fos_user_change_password:
    path:     /app/setting/password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods:  [GET, POST]