user_billing_history:
    path:     /transactions/billing-history
    defaults: { _controller: UniversalIDTBundle:Orders:index }

user_order_details:
    path:     /transactions/{id}/order
    defaults: { _controller: UniversalIDTBundle:Orders:details }

user_my_pins:
    path:     /my-pins
    defaults: { _controller: UniversalIDTBundle:Pins:index }

user_pin_details:
    path:     /my-pins/{id}/details
    defaults: { _controller: UniversalIDTBundle:Pins:details }

user_checkout:
    path:     /checkout
    defaults: { _controller: UniversalIDTBundle:Checkout:checkout }

user_ogone_result:
    path:     /checkout/ogone-result
    defaults: { _controller: UniversalIDTBundle:Checkout:ogoneResult }

user_sofort_result:
    path:     /checkout/sofort-result
    defaults: { _controller: UniversalIDTBundle:Checkout:sofortResult }
