user_profile_notification:
    path:     /setting/notification
    defaults: { _controller: UniversalIDTBundle:User:notification }

user_profile_email:
    path:     /setting/email
    defaults: { _controller: UniversalIDTBundle:User:email }

user_profile_email_confirm:
    path:     /setting/email/confirm/{token}
    defaults: { _controller: UniversalIDTBundle:User:emailConfirmed }

user_billing_history:
    path:     /transactions
    defaults: { _controller: UniversalIDTBundle:Orders:index }

user_order_details:
    path:     /transactions/{id}
    defaults: { _controller: UniversalIDTBundle:Orders:details }

user_pins:
    path:     /pins
    defaults: { _controller: UniversalIDTBundle:Pins:index }

user_pin_details:
    path:     /pins/{id}
    defaults: { _controller: UniversalIDTBundle:Pins:details }

user_checkout:
    path:     /checkout
    defaults: { _controller: UniversalIDTBundle:Checkout:checkout }

user_ogone_result:
    path:     /checkout/ogone-result
    defaults: { _controller: UniversalIDTBundle:Checkout:ogoneResult }

user_sofort_result:
    path:     /checkout/sofort-result
    defaults: { _controller: UniversalIDTBundle:Checkout:sofortResult }
