user_home:
    path:     /
    defaults: { _controller: UniversalIDTBundle:User:Home }

user_profile_notification:
    path:     /setting/notification
    defaults: { _controller: UniversalIDTBundle:User:notification }

user_profile_email:
    path:     /setting/email
    defaults: { _controller: UniversalIDTBundle:User:email }

user_orders:
    path:     /transactions
    defaults: { _controller: UniversalIDTBundle:Orders:index }

user_order_details:
    path:     /transactions/{id}
    defaults: { _controller: UniversalIDTBundle:Orders:details }

user_order_details_print:
    path:     /transactions/{id}/print
    defaults: { _controller: UniversalIDTBundle:Orders:detailsPrint }

user_pins:
    path:     /pins
    defaults: { _controller: UniversalIDTBundle:Pins:index }

user_pin_details:
    path:     /pins/{id}
    defaults: { _controller: UniversalIDTBundle:Pins:details }

user_checkout:
    path:     /checkout
    defaults: { _controller: UniversalIDTBundle:Checkout:checkout }

user_ogone_result:
    path:     /checkout/ogone-result
    defaults: { _controller: UniversalIDTBundle:Checkout:ogoneResult }

user_sofort_result:
    path:     /checkout/sofort-result
    defaults: { _controller: UniversalIDTBundle:Checkout:sofortResult }

user_sofort_notification:
    path:     /checkout/sofort-notification
    defaults: { _controller: UniversalIDTBundle:Checkout:sofortNotification }

user_result_print:
    path:     /checkout/result/{id}/print
    defaults: { _controller: UniversalIDTBundle:Checkout:UserResultPrint }
