WebPage_main:
    path:     /
    defaults: { _controller: UniversalIDTBundle:WebPage:main }

WebPage_card_list:
    path:     /calling_cards/list
    defaults: { _controller: UniversalIDTBundle:WebPage:cardsList }

WebPage_card_details:
    path:     /calling_cards/details
    defaults: { _controller: UniversalIDTBundle:WebPage:cardDetails }

WebPage_rates:
    path:     /rates
    defaults: { _controller: UniversalIDTBundle:WebPage:rates }

WebPage_rates_result:
    path:     /rates/result
    defaults: { _controller: UniversalIDTBundle:WebPage:ratesResult }

WebPage_basket:
    path:     /basket
    defaults: { _controller: UniversalIDTBundle:WebPage:basket }

WebPage_contact:
    path:     /contact
    defaults: { _controller: UniversalIDTBundle:WebPage:contact }

WebPage_checkout:
    path:     /checkout
    defaults: { _controller: UniversalIDTBundle:Checkout:checkout }

WebPage_ogone_result:
    path:     /checkout/ogone-result
    defaults: { _controller: UniversalIDTBundle:Checkout:ogoneResult }

WebPage_sofort_result:
    path:     /checkout/sofort-result
    defaults: { _controller: UniversalIDTBundle:Checkout:sofortResult }

WebPage_order_details:
    path:     /checkout/order-details
    defaults: { _controller: UniversalIDTBundle:Checkout:orderDetails }
