universal_user:
    resource: "@UniversalUserBundle/Resources/config/routing.xml"
    prefix:   /

universal_idt:
    resource: "@UniversalIDTBundle/Resources/config/routing.yml"
    prefix:   /

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
