security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                success_handler: universal_idt.login_handler
                default_target_path: user_home
            remember_me:
                key: 8regj4wtu4bh3o
            logout:
                path:     fos_user_security_logout
                success_handler: universal_idt.logout_success_handler
            anonymous:    true

    access_control:
        - { path: ^/[^/]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/admin/, role: ROLE_ADMIN }
        - { path: ^/[^/]+/app/, role: ROLE_USER }