guest:
    resource: "@UniversalIDTBundle/Resources/config/routing/guest.yml"
    prefix:   /

user:
    resource: "@UniversalIDTBundle/Resources/config/routing/user.yml"
    prefix:   /app

test:
    path:     /test
    defaults: { _controller: UniversalIDTBundle:Default:index }

checkout:
    resource: "@UniversalIDTBundle/Resources/config/routing/checkout.yml"
    prefix:   /checkout
