WebPage:
    resource: "@UniversalIDTBundle/Resources/config/routing/WebPage.yml"
    prefix:   /

user:
    resource: "@UniversalIDTBundle/Resources/config/routing/user.yml"
    prefix:   /app

fos_user:
    resource: "@UniversalIDTBundle/Resources/config/routing/fos_user.yml"
    prefix:   /

ogone_template:
    path:   /ogone_template
    defaults:
        _controller: FrameworkBundle:Template:template
        template: UniversalIDTBundle:PaymentGateWay:ogoneTemplate.html.twig

user_profile_email_confirm:
    path:     /change-email/confirm/{token}
    defaults: { _controller: UniversalIDTBundle:User:emailConfirmed }
