guest:
    resource: "@UniversalIDTBundle/Resources/config/routing/guest.yml"
    prefix:   /

test:
    path:     /test
    defaults: { _controller: UniversalIDTBundle:Default:index }

checkout:
    resource: "@UniversalIDTBundle/Resources/config/routing/checkout.yml"
    prefix:   /checkout