services:
    IDT:
        class: Universal\IDTBundle\Idt\ClientIdt
        arguments: [%IDT%, @guzzle.client, @doctrine.orm.default_entity_manager]

    universal_idt.registration.form.type:
        class: Universal\IDTBundle\Form\FOS\RegistrationFormType
        arguments: [%languages%]
        tags:
            - { name: form.type, alias: universal_idt_registration }

    client_ogone:
        class: Universal\IDTBundle\PaymentGateway\ClientOgone
        arguments: [@request, @router, @doctrine.orm.default_entity_manager, %Ogone%]
        scope: request

    universal_idt.fos_listener:
        class: Universal\IDTBundle\EventListener\FOSListener
        tags:
            - { name: kernel.event_subscriber }

#    universal_idt.example:
#        class: Universal\IDTBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
