parameters:
    IDT:
        username: "HellobellTEST1"
        password: "Humbug15ay"
        api_location: "https://app1.idt.net/debit/partner/partnerAPI.asp"

services:
    IDT:
        class: Universal\IDTBundle\Service\IDT
        arguments: [%IDT%, @guzzle.client, @doctrine.orm.default_entity_manager]
    universal_idt.registration.form.type:
        class: Universal\IDTBundle\Form\FOS\RegistrationFormType
        arguments: [%locales%]
        tags:
            - { name: form.type, alias: universal_idt_registration }
#    universal_idt.example:
#        class: Universal\IDTBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
