services:
    IDT:
        class: Universal\IDTBundle\Idt\ClientIdt
        arguments: [%IDT%, @guzzle.client, @doctrine.orm.default_entity_manager]

    universal_idt.registration.form.type:
        class: Universal\IDTBundle\Form\FOS\RegistrationFormType
        arguments: [%languages%, %countries%, @request]
        tags:
            - { name: form.type, alias: universal_idt_registration }
        scope: request

    universal_idt.profile.form.type:
        class: Universal\IDTBundle\Form\FOS\ProfileFormType
        arguments: [%languages%, %countries%]
        tags:
            - { name: form.type, alias: universal_idt_profile }

    client_ogone:
        class: Universal\IDTBundle\PaymentGateway\ClientOgone
        arguments: [@request, @router, @doctrine.orm.default_entity_manager, @security.authorization_checker, %Ogone%]
        scope: request

    client_sofort:
        class: Universal\IDTBundle\PaymentGateway\ClientSofort
        arguments: [@request, @router, @doctrine.orm.default_entity_manager, @security.authorization_checker, %Sofort%, @guzzle.client]
        scope: request

    universal_idt.fos_listener:
        class: Universal\IDTBundle\EventListener\FOSListener
        arguments: [ @router, @white_october_breadcrumbs, @translator.default ]
        tags:
            - { name: kernel.event_subscriber }

    universal_idt.login_handler:
        class: Universal\IDTBundle\EventListener\AuthenticationSuccessHandler
        arguments: [ @router, @security.http_utils, [] ]
        calls:
            - [ setProviderKey, ["main"] ]

    universal_idt.logout_success_handler:
            class: Universal\IDTBundle\EventListener\LogoutSuccessHandler
            arguments: [ @security.http_utils, "/" ]

    OrderServices:
        class: Universal\IDTBundle\Services\OrderServices
        arguments: [@doctrine.orm.default_entity_manager]

    EmailService:
            class: Universal\IDTBundle\Services\EmailService
            arguments: [@mailer]
#    universal_idt.example:
#        class: Universal\IDTBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
